"""add fipe_cache acao column

Revision ID: 20d4cc8a430e
Revises: 85a5039acfca
Create Date: 2026-05-24 12:27:20.606723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d4cc8a430e'
down_revision: Union[str, Sequence[str], None] = '85a5039acfca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fipe_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acao', sa.String(length=40), nullable=False, server_default=""))
        batch_op.drop_constraint(batch_op.f('uq_fipe_cache_query'), type_='unique')
        batch_op.create_unique_constraint('uq_fipe_cache_query', ['tipo', 'acao', 'marca_id', 'modelo_id', 'ano_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fipe_cache', schema=None) as batch_op:
        batch_op.drop_constraint('uq_fipe_cache_query', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_fipe_cache_query'), ['tipo', 'marca_id', 'modelo_id', 'ano_id'])
        batch_op.drop_column('acao')

    # ### end Alembic commands ###
