"""initial schema

Revision ID: f7c4f92f22d2
Revises: 
Create Date: 2026-05-24 09:08:43.353966

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f7c4f92f22d2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('chave', sa.String(length=80), nullable=False),
    sa.Column('valor_json', sa.String(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('fipe_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('marca_id', sa.String(length=40), nullable=True),
    sa.Column('modelo_id', sa.String(length=40), nullable=True),
    sa.Column('ano_id', sa.String(length=40), nullable=True),
    sa.Column('payload_json', sa.String(), nullable=False),
    sa.Column('coletado_em', sa.DateTime(), nullable=False),
    sa.Column('ttl_horas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo', 'marca_id', 'modelo_id', 'ano_id', name='uq_fipe_cache_query')
    )
    op.create_table('indicators_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=False),
    sa.Column('fonte', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.String(), nullable=True),
    sa.Column('coletado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', 'data_referencia', name='uq_indicator_codigo_data')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('pin_hash', sa.String(length=120), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fonte', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=80), nullable=False),
    sa.Column('modelo', sa.String(length=120), nullable=False),
    sa.Column('ano_modelo', sa.Integer(), nullable=False),
    sa.Column('combustivel', sa.String(length=40), nullable=False),
    sa.Column('codigo_fipe', sa.String(length=40), nullable=True),
    sa.Column('valor_fipe', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valor_referencia', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('mes_referencia_fipe', sa.String(length=40), nullable=True),
    sa.Column('snapshot_json', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=80), nullable=False),
    sa.Column('entidade', sa.String(length=40), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('diff_json', sa.String(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('hostname', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=80), nullable=False),
    sa.Column('valor_json', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=2), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('data_nasc', sa.Date(), nullable=True),
    sa.Column('profissao', sa.String(length=100), nullable=True),
    sa.Column('renda', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('endereco_json', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('valor_veiculo', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_entrada', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pct_entrada', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('prazo_meses', sa.Integer(), nullable=False),
    sa.Column('taxa_juros_mes', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('taxa_juros_ano', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('data_liberacao', sa.Date(), nullable=False),
    sa.Column('data_primeiro_venc', sa.Date(), nullable=False),
    sa.Column('dias_carencia', sa.Integer(), nullable=False),
    sa.Column('incluir_iof', sa.Boolean(), nullable=False),
    sa.Column('iof_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tarifas_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('extras_total_acumulado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_financiado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_parcela', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_pago', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_juros', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pct_juros', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('cet_mes', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('cet_ano', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rules_snapshot_json', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('amortization_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('numero_parcela', sa.Integer(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('dias_periodo', sa.Integer(), nullable=False),
    sa.Column('saldo_anterior', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('juros', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amortizacao', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('parcela', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('saldo_devedor', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('extras_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('parcela_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('ajuste_arredondamento', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('amortization_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amortization_rows_simulation_id'), ['simulation_id'], unique=False)  # noqa: E501

    op.create_table('comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_a_id', sa.Integer(), nullable=False),
    sa.Column('simulation_b_id', sa.Integer(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['simulation_a_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['simulation_b_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraordinary_amortizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('modo', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('aplicado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('gerado_por', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.String(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('validade_dias', sa.Integer(), nullable=False),
    sa.Column('gerado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['gerado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('simulation_extras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('modalidade', sa.String(length=30), nullable=False),
    sa.Column('duracao_meses', sa.Integer(), nullable=False),
    sa.Column('valor_por_parcela', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('incluir_no_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_fees')
    op.drop_table('simulation_extras')
    op.drop_table('proposals')
    op.drop_table('extraordinary_amortizations')
    op.drop_table('comparisons')
    with op.batch_alter_table('amortization_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amortization_rows_simulation_id'))

    op.drop_table('amortization_rows')
    op.drop_table('simulations')
    op.drop_table('clients')
    op.drop_table('business_rules')
    op.drop_table('audit_log')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('indicators_history')
    op.drop_table('fipe_cache')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
