"""StorageBackend Protocol."""
from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class StorageBackend(Protocol):
    async def put(self, key: str, data: bytes, content_type: str) -> str: ...
    async def get(self, key: str) -> bytes: ...
    async def signed_url(self, key: str, expires_in: int = 300) -> str: ...
    async def delete(self, key: str) -> None: ...
